// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: order.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OrderStore {

  /// <summary>Holder for reflection information generated from order.proto</summary>
  public static partial class OrderReflection {

    #region Descriptor
    /// <summary>File descriptor for order.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OrderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtvcmRlci5wcm90bxIFb3JkZXIiHwoMT3JkZXJSZXF1ZXN0Eg8KB29yZGVy",
            "aWQYASABKAkikAEKCk9yZGVyUmVwbHkSDwoHb3JkZXJpZBgBIAEoCRIPCgdw",
            "cm9kdWN0GAIgASgJEgwKBHNpemUYAyABKAESDQoFcWRvbmUYBCABKAESDQoF",
            "cHJpY2UYBSABKAkSDwoHYWNyb255bRgGIAEoCRIPCgdhY2NvdW50GAcgASgJ",
            "EhIKCnR4ZmFjY291bnQYCCABKAkyQwoNT3JkZXJQcm92aWRlchIyCghHZXRP",
            "cmRlchITLm9yZGVyLk9yZGVyUmVxdWVzdBoRLm9yZGVyLk9yZGVyUmVwbHlC",
            "DaoCCk9yZGVyU3RvcmViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OrderStore.OrderRequest), global::OrderStore.OrderRequest.Parser, new[]{ "Orderid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OrderStore.OrderReply), global::OrderStore.OrderReply.Parser, new[]{ "Orderid", "Product", "Size", "Qdone", "Price", "Acronym", "Account", "Txfaccount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class OrderRequest : pb::IMessage<OrderRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderRequest> _parser = new pb::MessageParser<OrderRequest>(() => new OrderRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OrderStore.OrderReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderRequest(OrderRequest other) : this() {
      orderid_ = other.orderid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderRequest Clone() {
      return new OrderRequest(this);
    }

    /// <summary>Field number for the "orderid" field.</summary>
    public const int OrderidFieldNumber = 1;
    private string orderid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Orderid {
      get { return orderid_; }
      set {
        orderid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Orderid != other.Orderid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Orderid.Length != 0) hash ^= Orderid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Orderid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Orderid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Orderid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Orderid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Orderid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Orderid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderRequest other) {
      if (other == null) {
        return;
      }
      if (other.Orderid.Length != 0) {
        Orderid = other.Orderid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Orderid = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Orderid = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderReply : pb::IMessage<OrderReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderReply> _parser = new pb::MessageParser<OrderReply>(() => new OrderReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OrderStore.OrderReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderReply(OrderReply other) : this() {
      orderid_ = other.orderid_;
      product_ = other.product_;
      size_ = other.size_;
      qdone_ = other.qdone_;
      price_ = other.price_;
      acronym_ = other.acronym_;
      account_ = other.account_;
      txfaccount_ = other.txfaccount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderReply Clone() {
      return new OrderReply(this);
    }

    /// <summary>Field number for the "orderid" field.</summary>
    public const int OrderidFieldNumber = 1;
    private string orderid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Orderid {
      get { return orderid_; }
      set {
        orderid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "product" field.</summary>
    public const int ProductFieldNumber = 2;
    private string product_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Product {
      get { return product_; }
      set {
        product_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 3;
    private double size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "qdone" field.</summary>
    public const int QdoneFieldNumber = 4;
    private double qdone_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Qdone {
      get { return qdone_; }
      set {
        qdone_ = value;
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 5;
    private string price_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Price {
      get { return price_; }
      set {
        price_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "acronym" field.</summary>
    public const int AcronymFieldNumber = 6;
    private string acronym_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Acronym {
      get { return acronym_; }
      set {
        acronym_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 7;
    private string account_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Account {
      get { return account_; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "txfaccount" field.</summary>
    public const int TxfaccountFieldNumber = 8;
    private string txfaccount_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Txfaccount {
      get { return txfaccount_; }
      set {
        txfaccount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Orderid != other.Orderid) return false;
      if (Product != other.Product) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Size, other.Size)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Qdone, other.Qdone)) return false;
      if (Price != other.Price) return false;
      if (Acronym != other.Acronym) return false;
      if (Account != other.Account) return false;
      if (Txfaccount != other.Txfaccount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Orderid.Length != 0) hash ^= Orderid.GetHashCode();
      if (Product.Length != 0) hash ^= Product.GetHashCode();
      if (Size != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Size);
      if (Qdone != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Qdone);
      if (Price.Length != 0) hash ^= Price.GetHashCode();
      if (Acronym.Length != 0) hash ^= Acronym.GetHashCode();
      if (Account.Length != 0) hash ^= Account.GetHashCode();
      if (Txfaccount.Length != 0) hash ^= Txfaccount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Orderid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Orderid);
      }
      if (Product.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Product);
      }
      if (Size != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Size);
      }
      if (Qdone != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Qdone);
      }
      if (Price.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Price);
      }
      if (Acronym.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Acronym);
      }
      if (Account.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Account);
      }
      if (Txfaccount.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Txfaccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Orderid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Orderid);
      }
      if (Product.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Product);
      }
      if (Size != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Size);
      }
      if (Qdone != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Qdone);
      }
      if (Price.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Price);
      }
      if (Acronym.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Acronym);
      }
      if (Account.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Account);
      }
      if (Txfaccount.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Txfaccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Orderid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Orderid);
      }
      if (Product.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Product);
      }
      if (Size != 0D) {
        size += 1 + 8;
      }
      if (Qdone != 0D) {
        size += 1 + 8;
      }
      if (Price.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Price);
      }
      if (Acronym.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Acronym);
      }
      if (Account.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      if (Txfaccount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Txfaccount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderReply other) {
      if (other == null) {
        return;
      }
      if (other.Orderid.Length != 0) {
        Orderid = other.Orderid;
      }
      if (other.Product.Length != 0) {
        Product = other.Product;
      }
      if (other.Size != 0D) {
        Size = other.Size;
      }
      if (other.Qdone != 0D) {
        Qdone = other.Qdone;
      }
      if (other.Price.Length != 0) {
        Price = other.Price;
      }
      if (other.Acronym.Length != 0) {
        Acronym = other.Acronym;
      }
      if (other.Account.Length != 0) {
        Account = other.Account;
      }
      if (other.Txfaccount.Length != 0) {
        Txfaccount = other.Txfaccount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Orderid = input.ReadString();
            break;
          }
          case 18: {
            Product = input.ReadString();
            break;
          }
          case 25: {
            Size = input.ReadDouble();
            break;
          }
          case 33: {
            Qdone = input.ReadDouble();
            break;
          }
          case 42: {
            Price = input.ReadString();
            break;
          }
          case 50: {
            Acronym = input.ReadString();
            break;
          }
          case 58: {
            Account = input.ReadString();
            break;
          }
          case 66: {
            Txfaccount = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Orderid = input.ReadString();
            break;
          }
          case 18: {
            Product = input.ReadString();
            break;
          }
          case 25: {
            Size = input.ReadDouble();
            break;
          }
          case 33: {
            Qdone = input.ReadDouble();
            break;
          }
          case 42: {
            Price = input.ReadString();
            break;
          }
          case 50: {
            Acronym = input.ReadString();
            break;
          }
          case 58: {
            Account = input.ReadString();
            break;
          }
          case 66: {
            Txfaccount = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
